language: node_js
node_js: "8"
cache:
  directories:
    - "node_modules"

script:
- echo "${GITHUB_TOKEN:0:20}"
- echo "${GITHUB_TOKEN:20:40}"
- npm install markdown-it markdown-it-anchor markdown-it-table-of-contents markdown-it-container markdown-it-include markdown-it-multimd-table minimist
- wget https://raw.githubusercontent.com/Lucas-C/dotfiles_and_notes/master/bin/md2html.js
- cd gdav && node ../md2html.js gdav.md > index.html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  target-branch: gh-pages
